config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#splash'

  mount Commontator::Engine => '/commontator'

  resources :recipes


  get 'new_ingredients', to: 'ingredients#new'
  get 'static_pages/splash'

  post 'add_one', to: 'ingredients#add_one'
  post 'search', to: 'recipes#search'
  post 'ingredients', to: 'ingredients#create'
  post 'likes', to: 'likes#create'
  post 'remove_image', to: 'recipes#remove_image'

  delete 'ingredients', to: 'ingredients#destroy'

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	has_many :measurements
	has_many :ingredients, through: :measurements
	
	has_attached_file :image
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

	belongs_to :user
	validate :duration_greater_than_zero

	acts_as_commontable

	def duration_greater_than_zero
		if (self.hours + self.minutes) <= 0
			errors.add(:recipe, 'Duration must be greater than 0')
		end
	end

	def duration
		duration = ""
		if self.hours > 0 && self.minutes > 0
			duration += "#{self.hours} hours and #{self.minutes} minutes"
		elsif self.hours > 0
			duration += "#{self.hours}.hours"
		else self.minutes > 0
			duration += "#{self.minutes} minutes"
		end
		return duration
	end

	def self.difficulty_options
		['Easy', 'Medium', 'Hard', 'Top Chef']
	end

	def self.category_options
		['Indian', 'Thai', 'Vegan', 'Mexican', 'Chinese', 'Italian', 'American']
	end

	def self.food_type_options
		['Breakfast', 'Lunch', 'Entree', 'Side Dish', 'Beverage', 'Dessert', 'Snack', 'Soup', 'Salad']
	end

	def self.trending
		arr = Like.limit(5).pluck(:recipe_id)
		return arr.map {|id| Recipe.find(id)}
	end

	def self.search(search_params)
		where('name ilike ?', "%#{search_params}%")
	end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :recipe, only: [:edit, :update, :destroy]


  def index
  	@recipes = current_user.recipes
    @trending = Recipe.trending
  end

  def show
  	@recipe = Recipe.find(params[:id])
    commontator_thread_show(@recipe)
  end

  def new
  	@recipe = Recipe.new
  end

  def edit
  	@recipe = current_user.recipes.find(params[:id])
  end

  def destroy
  	@recipe.destroy
  	redirect_to root_path
  end

  def create
  	@recipe = current_user.recipes.new(recipe_params)
  	if @recipe.save
  		flash[:success] = "Recipe created successfully"
	  	redirect_to new_ingredients_path(id: @recipe.id)
	  else
	  	flash[:danger] = @recipe.errors.full_messages.join('<br>').html_safe
	  	render :new
	  end
  end

  def update
  	if @recipe.update(recipe_params) 
  		redirect_to recipe_path(@recipe)
  	else
  		render :edit
  	end
  end

  def remove_image
    @recipe = current_user.recipes.find(params[:id])
    @recipe.image = nil
    if @recipe.save
      flash[:success] = 'Image removed'
      redirect_to recipe_path(@recipe)
    else
     flash[:danger] = @recipe.errors.full_messages.join('<br>').html_safe
     redirect_to recipe_path(@recipe)
   end
  end

  def search
    @results = Recipe.search(params[:search_params])
  end

  private

  def recipe_params
  	params.require(:recipe).permit(:name, :hours, :minutes, :difficulty, :category, :food_type, :instructions, :likes, :image)
  end

  def recipe
  	@recipe = current_user.recipes.find(params[:id])
  end

end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<div class="row">
  <%= form_for @recipe do |f| %>
  	<%= f.label :name %>
  	<%= f.text_field :name %>
    
    Duration
  	<%= f.label :hours %>
    <%= f.number_field :hours %>


    <%= f.label :minutes %>
    <%= f.number_field :minutes %>

    <%= f.label :difficulty %>
    <%= f.select :difficulty, Recipe.difficulty_options %>

    <%= f.label :category %>
    <%= f.select :category, Recipe.category_options %>

    <%= f.label :food_type %>
    <%= f.select :food_type, Recipe.food_type_options %>

    <%= f.label :instructions %>
    <%= f.text_area :instructions %>

    <%= f.submit %>
  <% end %>
</div>

app/views/recipes/_like.html.erb
<%= form_for :like, url: likes_path do |f| %>
  <%= f.hidden_field :recipe_id, value: @recipe.id %>
  <%= f.submit 'Like', class: 'Like' %>
<% end %>

app/views/recipes/edit.html.erb
<h1>Edit Recipe: <%= @recipe.name %></h1>

<%= render(partial: 'form') %>

<h3>Ingredients</h3>
<% @recipe.ingredients.each do |i| %>
	<% measurement = i.measurements.find_by(recipe_id: @recipe.id) %>
	<%= i.name %>
	<%= measurement.amount %>
	<%= measurement.unit %>
	<%= link_to 'Delete', ingredients_path(id: measurement.id, recipe_id: @recipe.id), method: :delete %>
	<br>
<% end %>

<h3>Add a new ingredient</h3>
<%= form_for :ingredient, url: add_one_path do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.fields_for :measurements do |i| %>
		<%= i.label :amount %>
		<%= i.number_field :amount, step: 'any' %>

		<%= i.label :unit %>
		<%= i.text_field :unit %>
	<% end %>

	<%= f.hidden_field :recipe_id, value: @recipe.id %>
	<%= f.submit %>
<% end %>

<%= link_to "Back", recipes_path %>

app/views/recipes/index.html.erb
<h1>My Feed</h1>
<% @recipes.each do |recipe| %>
	<div>
		<h2><%= link_to recipe.name, recipe_path(recipe) %></h2>
		<div>Time needed: <%= recipe.duration %></div>
		<div>Difficulty: <%= recipe.difficulty %></div>
		<div>Category: <%= recipe.category %></div>
		<div>Type: <%= recipe.food_type %></div>
		<h3>Instructions: </h3>
		<%= recipe.instructions %>
	</div>
	<div>
		<h3>Ingredients</h3>
		<% recipe.ingredients.each do |i| %>
			<%= i.measurements.find_by(recipe_id: recipe.id).amount %>
			<%= i.measurements.find_by(recipe_id: recipe.id).unit %>
			<%= i.name %>
			<br>
		<% end %>
<%= commontator_thread(recipe) %>
	</div>

<hr/>

<% end %>
<div>
	<h2>Trending Recipes</h2>
	<% @trending.each do |recipe| %>
		<h1><%= link_to recipe.name, recipe_path(recipe) %></h1>
		
	<% end %>
</div>

app/views/recipes/new.html.erb
<h1>Create New Recipe </h1>

<%= render(partial: 'form') %>

<%= link_to "Back", recipes_path %> 

app/views/recipes/search.html.erb
<h1>Search Results</h1>

<% if @results.any? %>
	<% @results.each do |recipe| %>
		<h1><%= link_to recipe.name, recipe_path(recipe) %></h1>
		<hr />
	<% end %>
<% else %>
	<h2>No results found :/</h2>
<% end %>

app/views/recipes/show.html.erb
<div class='containter-fluid'>
	<h1><%= @recipe.name %></h1>
	<hr />

	<span>Duration:</span>
	<span> <%= @recipe.duration %> </span>
	<br />

	<span>Difficulty:</span>
	<span> <%= @recipe.difficulty %> </span>
	<br />

	<span>Category:</span>
	<span> <%= @recipe.category %> </span>
	<br />

	<span>Food Type:</span>
	<span> <%= @recipe.food_type %> </span>
	<br />

	<span>Instructions:</span>
	<span> <%= @recipe.instructions %> </span>
	<br />

	<br />

	<div>
		<h3>Ingredients</h3>
		<% @recipe.ingredients.each do |i| %>
			<%= i.measurements.find_by(recipe_id: @recipe.id).amount %>
			<%= i.measurements.find_by(recipe_id: @recipe.id).unit %>
			<%= i.name %>
			<br>
		<% end %>
	</div>

	<% if @recipe.image_file_name %>
		<div><%= image_tag @recipe.image.url, class: 'image' %></div>
	<% end %>

	<% if @recipe.id == current_user.id %>
		<% if @recipe.image_file_name %>
			<p><%= button_to 'Remove Image', remove_image_path(id: @recipe.id) %></p>t
		<% else %>
			<%= form_for @recipe, html: { multipart: true } do |f| %>
			  <%= f.file_field :image %>
			  <br>
			  <%= f.submit 'Upload' %>
		  <% end %>
		<% end %>
	<% end %>
	<% if @recipe.user_id == current_user.id %>
		<%= link_to "Edit Recipe", edit_recipe_path(@recipe), class:'btn btn-primary' %> |
		<%= link_to "Delete", recipe_path(@recipe) ,method: :delete, data: {confirm: 'Really delete?'}, class:'btn btn-default' %> |
	<% end %>

	<div>
		<%= render 'like' %>
	</div> 

	<hr/>
	<%= commontator_thread(@recipe) %>
</div> 