config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#splash'

  mount Commontator::Engine => '/commontator'

  resources :recipes


  get 'new_ingredients', to: 'ingredients#new'
  get 'static_pages/splash'

  post 'add_one', to: 'ingredients#add_one'
  post 'search', to: 'recipes#search'
  post 'ingredients', to: 'ingredients#create'
  post 'likes', to: 'likes#create'
  post 'remove_image', to: 'recipes#remove_image'

  delete 'ingredients', to: 'ingredients#destroy'

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
end

app/views/layouts/_navbar.html.erb
<header>
  <nav>
    <div class="nav-wrapper">
      <div class="container">
        <a href="#!" class="brand-logo">FEED!</a>
        <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
          <li>
            <div>
              <%= form_tag('/search') do %>
                  <%= text_field_tag :search_params %>
                  <%= submit_tag "Search", :style => "visibility: hidden;" %>
              <% end %>
            </div>
          </li>
          <li><%= link_to "Your Feed", recipes_path %></li>
          <li><%= link_to "Add Recipe", new_recipe_path %></li>
          <% if current_user %>
            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete  %></li>
          <% end %>
        </ul>
        <ul class="side-nav" id="mobile-demo">
          <li>
            <div>
              <%= form_tag('/search') do %>
                  <%= text_field_tag :search_params %>
                  <%= submit_tag "Search", :style => "visibility: hidden;" %>
              <% end %>
            </div>
          </li>
          <li><%= link_to "Your Feed", recipes_path %></li>
          <li><%= link_to "Add", new_recipe_path %></li>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FeedApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>

<body>

<%= render(partial: '/layouts/navbar') %>

<div class="container">
  <%= yield %>
</div>
</body>


</html>